name: Check and build Dockerfile

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}', github.run_id, github.run_attempt) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/nilfoundation/proof-market-toolchain

jobs:
  build-image:
    runs-on: [ self-hosted, aws_autoscaling ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build a Docker image
        run: |
          set -xe
          docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Build proof market in a container
        run: |
          set -xe
          docker run -t \
            -v $(pwd):/proof-market-toolchain \
            ghcr.io/nilfoundation/proof-market-toolchain:latest sh ./build.sh
